"""
Setup script for the Personal AI Employee Hackathon vault

This script creates all required directories and initial files for the Silver tier project.
"""

import os
from pathlib import Path


def setup_vault():
    """Create the required folder structure and initial files"""
    base_dir = Path(__file__).parent

    # Create all required directories
    directories = [
        'Inbox',
        'Needs_Action',
        'Plans',
        'Pending_Approval',
        'Approved',
        'Rejected',
        'Done',
        'Logs',
        'Briefings',
        'Updates',
        'Accounting',
        'Invoices',
        'expense-policy-enforcer'  # Already exists but let's ensure it's set up
    ]

    for directory in directories:
        dir_path = base_dir / directory
        dir_path.mkdir(exist_ok=True)
        print(f"Created directory: {dir_path}")

    # Create/update Dashboard.md if it doesn't exist
    dashboard_path = base_dir / "Dashboard.md"
    if not dashboard_path.exists():
        dashboard_content = """# Dashboard

## Pending Items Count
- Total pending: 0
- High priority: 0
- Due today: 0

## Recent Activity
- [2026-02-22 00:00] Vault setup complete

## System Status
- System health: OK
- Last sync: 2026-02-22
- Active workflows: 0
"""
        with open(dashboard_path, 'w') as f:
            f.write(dashboard_content)
        print(f"Created {dashboard_path}")

    # Ensure Company_Handbook.md is in place (should already exist)
    handbook_path = base_dir / "Company_Handbook.md"
    if not handbook_path.exists():
        handbook_content = """# Company Handbook

## Communication Rules
- All communications should be clear and respectful
- Use professional language in all interactions
- Respond to messages within 24 hours during business days
- Use appropriate channels for different types of discussions

## Financial Approval Rule
- Any expense above $100 requires prior approval from a manager
- Submit expense reports with receipts for reimbursement
- Keep records of all financial transactions

## Tone Guidelines
- Maintain a professional tone in all communications
- Be polite and courteous to colleagues and clients
- Keep messages concise and to the point
- Avoid jargon unless communicating with technical teams
"""
        with open(handbook_path, 'w') as f:
            f.write(handbook_content)
        print(f"Created {handbook_path}")

    # Create a basic README for the vault
    readme_path = base_dir / "README.md"
    readme_content = """# AI Employee Vault

This is the Obsidian vault for the Personal AI Employee Hackathon project.

## Folder Structure
- **Inbox**: Incoming files that need processing
- **Needs_Action**: Files requiring immediate attention
- **Plans**: Detailed plans generated by Claude
- **Pending_Approval**: Files requiring human approval before execution
- **Approved**: Files approved for action
- **Rejected**: Files rejected from processing
- **Done**: Completed tasks
- **Logs**: System logs and audit trails
- **Briefings**: Weekly business briefings
- **Updates**: System updates and signals

## Setup
The vault has been initialized with all required directories and files.
"""
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    print(f"Created {readme_path}")

    print("\nVault setup complete!")
    print("Directories created:")
    for directory in directories:
        print(f"  - {directory}")


if __name__ == "__main__":
    setup_vault()